# Generated by Django 5.2.7 on 2026-02-24 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateMetadata",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("modified", models.DateTimeField(auto_now=True, help_text="The date/time this resource was created.")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, help_text="The date/time this resource was created."),
                ),
                ("awx_created", models.DateTimeField(blank=True, help_text="Creation timestamp from AWX", null=True)),
                (
                    "awx_modified",
                    models.DateTimeField(blank=True, help_text="Modification timestamp from AWX", null=True),
                ),
                (
                    "template_id",
                    models.IntegerField(
                        db_index=True,
                        help_text="AWX job template ID (from AWX database main_jobtemplate table)",
                        unique=True,
                    ),
                ),
                (
                    "template_name",
                    models.CharField(db_index=True, help_text="Template name for display (from AWX)", max_length=512),
                ),
                (
                    "template_description",
                    models.TextField(blank=True, help_text="Template description for display (from AWX)"),
                ),
                (
                    "time_taken_manually_execute_minutes",
                    models.BigIntegerField(
                        blank=True,
                        help_text="User override: Estimated time to perform this task manually (minutes)",
                        null=True,
                    ),
                ),
                (
                    "time_taken_create_automation_minutes",
                    models.BigIntegerField(
                        blank=True,
                        help_text="User override: Estimated time spent creating this automation (minutes)",
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        help_text="The user who created this resource.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        help_text="The user who last modified this resource.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Template Metadata",
                "verbose_name_plural": "Template Metadata",
                "db_table": "dashboard_template_metadata",
                "ordering": ["template_name"],
            },
        ),
        migrations.CreateModel(
            name="JobData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("modified", models.DateTimeField(auto_now=True, help_text="The date/time this resource was created.")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, help_text="The date/time this resource was created."),
                ),
                ("awx_created", models.DateTimeField(blank=True, help_text="Creation timestamp from AWX", null=True)),
                (
                    "awx_modified",
                    models.DateTimeField(blank=True, help_text="Modification timestamp from AWX", null=True),
                ),
                (
                    "job_id",
                    models.IntegerField(
                        db_index=True, help_text="AWX job ID (from AWX database main_unifiedjob table)", unique=True
                    ),
                ),
                ("template_name", models.CharField(help_text="Job template name (from AWX)", max_length=512)),
                ("template_id", models.IntegerField(blank=True, help_text="AWX template ID", null=True)),
                ("project_id", models.IntegerField(blank=True, help_text="AWX project ID", null=True)),
                (
                    "project_name",
                    models.CharField(
                        blank=True, help_text="Project name for display (from AWX)", max_length=512, null=True
                    ),
                ),
                ("organization_id", models.IntegerField(blank=True, help_text="AWX organization ID", null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("pending", "Pending"),
                            ("waiting", "Waiting"),
                            ("running", "Running"),
                            ("successful", "Successful"),
                            ("failed", "Failed"),
                            ("error", "Error"),
                            ("canceled", "Canceled"),
                        ],
                        db_index=True,
                        default="successful",
                        max_length=25,
                    ),
                ),
                (
                    "started",
                    models.DateTimeField(
                        default=None,
                        help_text="Job start timestamp (from AWX database main_unifiedjob table)",
                        null=True,
                    ),
                ),
                (
                    "finished",
                    models.DateTimeField(
                        db_index=True,
                        default=None,
                        help_text="Job finish timestamp (from AWX database main_unifiedjob table)",
                        null=True,
                    ),
                ),
                (
                    "elapsed",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Job elapsed time in seconds (from AWX database main_unifiedjob table)",
                        max_digits=15,
                    ),
                ),
                (
                    "num_hosts",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of hosts involved in the job (calculated from AWX job host summaries)",
                    ),
                ),
                (
                    "changed_hosts_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of hosts that were changed during the job (calculated from AWX job host summaries)",
                    ),
                ),
                ("dark_hosts_count", models.PositiveIntegerField(default=0)),
                ("failures_hosts_count", models.PositiveIntegerField(default=0)),
                ("ok_hosts_count", models.PositiveIntegerField(default=0)),
                ("processed_hosts_count", models.PositiveIntegerField(default=0)),
                ("skipped_hosts_count", models.PositiveIntegerField(default=0)),
                ("failed_hosts_count", models.PositiveIntegerField(default=0)),
                ("ignored_hosts_count", models.PositiveIntegerField(default=0)),
                ("rescued_hosts_count", models.PositiveIntegerField(default=0)),
                (
                    "launched_by_id",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        help_text="AWX user ID of the user who launched the job (from AWX database main_unifiedjob table)",
                        null=True,
                    ),
                ),
                (
                    "launched_by_username",
                    models.CharField(
                        blank=True,
                        help_text="AWX username of the user who launched the job (from AWX database main_unifiedjob table)",
                        max_length=512,
                        null=True,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        help_text="The user who created this resource.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        help_text="The user who last modified this resource.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "template_metadata",
                    models.ForeignKey(
                        blank=True,
                        help_text="Reference to TemplateMetadata for this job's template",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="dashboard_reports.templatemetadata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Data",
                "verbose_name_plural": "Jobs Data",
                "db_table": "dashboard_job_data",
                "ordering": ["-started"],
            },
        ),
        migrations.CreateModel(
            name="JobHostSummary",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("modified", models.DateTimeField(auto_now=True, help_text="The date/time this resource was created.")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, help_text="The date/time this resource was created."),
                ),
                (
                    "host_summary_id",
                    models.IntegerField(
                        blank=True,
                        help_text="AWX host summary ID (from AWX database main_hostsummary table)",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "host_id",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        help_text="AWX host ID (from AWX database main_host table)",
                        null=True,
                    ),
                ),
                (
                    "host_name",
                    models.TextField(db_index=True, help_text="Host name for display (from AWX)", max_length=512),
                ),
                ("changed", models.PositiveIntegerField(default=0)),
                ("dark", models.PositiveIntegerField(default=0)),
                ("failures", models.PositiveIntegerField(default=0)),
                ("ok", models.PositiveIntegerField(default=0)),
                ("processed", models.PositiveIntegerField(default=0)),
                ("skipped", models.PositiveIntegerField(default=0)),
                ("ignored", models.PositiveIntegerField(default=0)),
                ("rescued", models.PositiveIntegerField(default=0)),
                ("failed", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        help_text="The user who created this resource.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="host_summaries",
                        to="dashboard_reports.jobdata",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        help_text="The user who last modified this resource.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Data Host Summary",
                "verbose_name_plural": "Job Data Host Summaries",
                "db_table": "dashboard_job_data_host_summary",
                "indexes": [models.Index(fields=["job_data", "host_id"], name="dashboard_jhs_job_host_idx")],
            },
        ),
        migrations.CreateModel(
            name="JobLabel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("modified", models.DateTimeField(auto_now=True, help_text="The date/time this resource was created.")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, help_text="The date/time this resource was created."),
                ),
                ("label_id", models.IntegerField(blank=True, db_index=True, help_text="AWX label ID", null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        help_text="The user who created this resource.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels",
                        to="dashboard_reports.jobdata",
                    ),
                ),
                (
                    "modified_by",
                    models.ForeignKey(
                        default=None,
                        editable=False,
                        help_text="The user who last modified this resource.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_modified+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Data Label",
                "verbose_name_plural": "Job Data Labels",
                "db_table": "dashboard_job_data_label",
                "indexes": [models.Index(fields=["job_data", "label_id"], name="dashboard_jl_job_label_idx")],
            },
        ),
        migrations.AddIndex(
            model_name="templatemetadata",
            index=models.Index(fields=["template_id"], name="dashboard_tm_template_idx"),
        ),
        migrations.AddIndex(
            model_name="jobdata",
            index=models.Index(fields=["template_id"], name="dashboard_jd_template_idx"),
        ),
        migrations.AddIndex(
            model_name="jobdata",
            index=models.Index(fields=["project_id"], name="dashboard_jd_project_idx"),
        ),
        migrations.AddIndex(
            model_name="jobdata",
            index=models.Index(fields=["organization_id"], name="dashboard_jd_organization_idx"),
        ),
    ]
